disabled_rules: # rule identifiers to exclude from running
  - nesting
opt_in_rules: # some rules are only opt-in
  - cyclomatic_complexity
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

line_length: 140

identifier_name:
  excluded:
    - !str id
    - !str ID
    - !str Id
    - !str on
    - !str me
    - !str ds
    - !str tv
    - !str ip
    - !str x
    - !str y
    - !srt no

function_body_length:
  - 100